services:

  php-fpm:
    build:
      context: phpdocker/php-fpm
      args:
        - OPCACHE_VALIDATE_TIMESTAMPS=${OPCACHE_VALIDATE_TIMESTAMPS}
    container_name: ${PROJECT}-php-fpm
    user: ${PHP_UID}:${PHP_GID}
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini

  webserver:
    image: nginx:alpine
    container_name: ${PROJECT}-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${WEB_PORT}:80

  mysql:
    image: mysql:latest
    container_name: ${PROJECT}-mysql
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    ports:
      - ${MYSQL_DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_USER=${MYSQL_DB_USER}
      - MYSQL_PASSWORD=${MYSQL_DB_PASS}

  phpmyadmin:
    image: phpmyadmin
    container_name: ${PROJECT}-phpmyadmin
    depends_on:
      - mysql
    ports:
      - ${PMA_PORT}:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=${MYSQL_DB_USER}
      - PMA_PASSWORD=${MYSQL_DB_PASS}
